name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aprsc-docker:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: |
        docker tag aprsc-docker:$(date +%s) ${{ secrets.DOCKER_USERNAME }}/aprsc-docker:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/aprsc-docker:latest
    - name: Push the Docker image with timestamp
      run: |
        docker tag aprsc-docker:$(date +%s) ${{ secrets.DOCKER_USERNAME }}/aprsc-docker:$(date +%s)
        docker push ${{ secrets.DOCKER_USERNAME }}/aprsc-docker:$(date +%s)
    - name: Logout from Docker Hub
      run: docker logout
    - name: Cleanup Docker images 
      run: |
        docker rmi aprsc-docker:$(date +%s) || true
        docker rmi ${{ secrets.DOCKER_USERNAME }}/aprsc-docker:latest || true
        docker rmi ${{ secrets.DOCKER_USERNAME }}/aprsc-docker:$(date +%s) || true
        docker system prune -f --volumes || true
        docker image prune -f || true
        docker container prune -f || true
        docker network prune -f || true
        docker volume prune -f || true
        docker builder prune -f || true
        docker system df -v || true
